selectPlayer('messi', 'Lionel Messi')
selectPlayer('neymar', 'Neymar Jr')
selectPlayer('mbappe', 'Kylian Mbappe')
selectPlayer('machado', 'Vitor Machado')
selectPlayer('ramos', 'Sergio Ramos')
selectPlayer('sanches', 'Renato Sanches')